config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :documents
  
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get 'sessions/create'
  get 'sessions/destroy'  
  
  root 'welcome#index'
  

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  PRODUCT_TYPES = ["X-17 Black", "X-17 White"]
  PAYMENT_TYPES = [ "Check", "Credit card", "Paypal" ]
  validates :name, :business, :email, :phone, presence: true
  validates :product, inclusion: PRODUCT_TYPES
  validates :payment, inclusion: PAYMENT_TYPES
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  after_destroy :ensure_an_admin_remains
  validates :name, :email, presence: true
  has_one :document, dependent: :destroy
  
  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end
  
  def filename
    @document.business
  end   
  
  def current_document
    @current_document ||= Document.find(session[:id])
  end 
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end  

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'Required_Documents',   # Excluding ".pdf" extension.
               layout: 'pdf.html.erb',
               template: 'documents/edit.pdf.erb',
               wkhtmltopdf: 'bin/wkhtmltopdf',
               page_height: '10',
               page_width: '10em'
      end
    end     
  end
  
  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)   

    respond_to do |format|
      if @document.save
        pdf = render_to_string pdf: "Required_Documents.pdf", 
        layout: 'pdf.html.erb', 
        template: "documents/edit.pdf.erb", 
        encoding: "UTF-8", 
        wkhtmltopdf: 'bin/wkhtmltopdf', 
        page_height: '10in', 
        page_width: '10em'
        save_path = Rails.root.join('pdfs',"#{filename}.Required_Documents.pdf")
        File.open(save_path, 'wb') do |file|
          file << pdf
        end   
        file = open(save_path)  
        client = DropboxClient.new(OAUTH2_ACCESS_TOKEN)
        response = client.put_file('Applications/' + filename + '.Required_Documents.pdf', file)                
        format.html { redirect_to root_path, notice: 'Documents were successfully uploaded.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end 

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    @document = Document.find(params[:id])
    
    respond_to do |format|
      if @document.update(document_params)
        pdf = render_to_string pdf: "Required_Documents.pdf", 
        layout: 'pdf.html.erb', 
        template: "documents/edit.pdf.erb", 
        encoding: "UTF-8", 
        wkhtmltopdf: 'bin/wkhtmltopdf', 
        page_height: '10in', 
        page_width: '10em'
        save_path = Rails.root.join('pdfs',"#{filename}.Required_Documents.pdf")
        File.open(save_path, 'wb') do |file|
          file << pdf
        end   
        file = open(save_path)  
        client = DropboxClient.new(OAUTH2_ACCESS_TOKEN)
        response = client.put_file('Applications/' + filename + '.Required_Documents.pdf', file, overwrite=true)               
        format.html { redirect_to current_user, notice: 'Documents were successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :business, :email, :phone, :product, :payment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if user and user.authenticate(params[:password]) and user[:admin]
      session[:user_id] = user.id
      redirect_to admin_url
    elsif user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user  
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
require 'dropbox_sdk'

class UsersController < ApplicationController
  skip_before_action :authorize  
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Thank you for registering.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User #{@user.name} was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documents/_form.html.erb
  <div class='jumbotron col-md-10 col-md-offset-1'>

    <%= form_for(@document) do |f| %>
      
      <% if @document.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>
          <ul>
            <% @document.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>  
      <% end %>
      
      <fieldset>
        <legend>Applicant Information</legend>
  
		<div class="form-group col-md-8 col-md-offset-2">
		  <%= f.label :name, "Applicant Name" %><br/>
	      <%= f.text_field :name, class: "form-control" %>
	    </div>  
  
	    <div class="form-group col-md-8 col-md-offset-2">
	      <%= f.label :business, "Name of Business" %><br/>
	      <%= f.text_field :business, class: "form-control" %>
	    </div>  
  
	    <div class="form-group col-md-8 col-md-offset-2">
	      <%= f.label :email, "Email" %><br/>
	      <%= f.email_field :email, class: "form-control" %>
	    </div>    
		     
	    <div class="form-group col-md-8 col-md-offset-2">
	      <%= f.label :phone, "Phone" %><br/>
	      <%= f.telephone_field :phone, class: "form-control" %>
	    </div>
	    
	    <div class="form-group col-md-2 col-md-offset-2">
	      <%= f.label :product, "Product" %><br/>
	      <%= f.select :product, Document::PRODUCT_TYPES, prompt: "Select a product type" %>
	    </div>
	    
	    <div class="form-group col-md-3 col-md-offset-2">
	      <%= f.label :payment, "Payment Method" %><br/>
	      <%= f.select :payment, Document::PAYMENT_TYPES, prompt: "Select a payment method"  %>
	    </div>    
	  </fieldset>

      <div class=" col-md-5 col-md-offset-4 actions">
        <%= f.submit "Submit Application", class: "btn btn-lg btn-primary" %>
      </div>
      
    <% end %>
    
  </div>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/edit.pdf.erb
  <div class='jumbotron col-md-10 col-md-offset-1'>

    <%= form_for(@document) do |f| %>
      
      <% if @document.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>
          <ul>
            <% @document.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>  
      <% end %>
      
      <fieldset>
        <legend>Applicant Information</legend>
  
		<div class="form-group col-md-8 col-md-offset-2">
		  <%= f.label :name, "Applicant Name" %><br/>
	      <%= f.text_field :name, class: "form-control" %>
	    </div>  
  
	    <div class="form-group col-md-8 col-md-offset-2">
	      <%= f.label :business, "Name of Business" %><br/>
	      <%= f.text_field :business, class: "form-control" %>
	    </div>  
  
	    <div class="form-group col-md-8 col-md-offset-2">
	      <%= f.label :email, "Email" %><br/>
	      <%= f.email_field :email, class: "form-control" %>
	    </div>    
		     
	    <div class="form-group col-md-8 col-md-offset-2">
	      <%= f.label :phone, "Phone" %><br/>
	      <%= f.telephone_field :phone, class: "form-control" %>
	    </div>
	    
	    <div class="form-group col-md-2 col-md-offset-2">
	      <%= f.label :product, "Product" %><br/>
	      <%= f.select :product, Document::PRODUCT_TYPES, prompt: "Select a product type" %>
	    </div>
	    
	    <div class="form-group col-md-3 col-md-offset-2">
	      <%= f.label :payment, "Payment Method" %><br/>
	      <%= f.select :payment, Document::PAYMENT_TYPES, prompt: "Select a payment method"  %>
	    </div>    
	  </fieldset>

      <div class=" col-md-5 col-md-offset-4 actions">
        <%= f.submit "Submit Application", class: "btn btn-lg btn-primary" %>
      </div>
      
    <% end %>
    
  </div>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<div class="col-md-12 text-center">
  <h1>New Application</h1>
</div>

<%= render 'form' %>

<div class="col-md-12 text-center back-buttons">
  <%= link_to 'Back', documents_path, class: "btn btn-lg btn-default" %>
</div>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Dropbox Send Forms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-inverse navbar-static-top">
  	<div class="container">
  	  <div class="navbar-header">
        <a href="#" class='navbar-brand'>
  	      Vectron Technologies
        </a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      	  <span class="sr-only">Toggle Navigation</span>
      	  <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse">
  	    <li><a href="#">Home</a></li>
  	    <li><a href="#">Products</a></li>
  	    <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>

  <div class= "container">
    <%= yield %>
  </div>

  <footer class="row">
  	<div class="container">
      <h4>Links</h4>
      <ul class="list-unstyled">
  	    <li><a href="#">Home</a></li>
  	    <li><a href="#">Products</a></li>
  	    <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </footer>

</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Dropbox Send Forms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-inverse navbar-static-top">
  	<div class="container">
  	  <div class="navbar-header">
        <a href="#" class='navbar-brand'>
  	      Vectron X-17 Wrist Computer
        </a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      	  <span class="sr-only">Toggle Navigation</span>
      	  <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse">
  	    <li><a href="#">Home</a></li>
  	    <li><a href="#">Products</a></li>
  	    <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>

  <div class= "container">
    <%= yield %>
  </div>

  <footer class="row">
  	<div class="container">
      <h4>Links</h4>
      <ul class="list-unstyled">
  	    <li><a href="#">Home</a></li>
  	    <li><a href="#">Products</a></li>
  	    <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </footer>

</body>
</html>

app/views/users/_form.html.erb
<div class="row">
  <div class="jumbotron col-md-6 col-md-offset-3">

	<%= form_for(@user) do |f| %>
	  <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
	
	      <ul>
	      <% @user.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  
      <form class="text-left">
		  <div class="form-group">
		    <%= f.label :name, "Name" %>
		    <%= f.text_field :name, class: "form-control" %>
		  </div> 
		  <div class="form-group">
		    <%= f.label :email %>
		    <%= f.text_field :email, class: "form-control" %>
		  </div>
		  <div class="form-group">
		    <%= f.label :password %>
		    <%= f.password_field :password, class: "form-control" %>
		  </div>
		  <div class="form-group">
		    <%= f.label :password_confirmation %>
		    <%= f.password_field :password_confirmation, class: "form-control" %>
		  </div>	  
	
	      <div class="actions">
	        <%= f.submit %>
	      </div>
	  </form>
	  
	<% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="col-md-12 text-center">
  <h1>Editing User</h1>
</div>

<%= render 'form' %>

<div class="col-md-12">
  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="col-md-12 text-center">
  <h1>New User</h1>
</div>

<%= render 'form' %>

<div class="col-md-12 text-center">
  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="profile">
  <div class="row">
    <div class="col-md-12 text-center">
      <p id="notice"><%= notice %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 text-center">
      <h1><%= @user.name %></h1>
      <p>
        <strong>Email:</strong>
        <%= @user.email %>	
      </p>
    </div>
  </div>

  <div class="row register-button">
    <div class="col-md-12 text-center">
        <% if @user.document %>
          <%= link_to "Edit Application", edit_document_path(@user.document), 
          class: "btn btn-lg btn-primary" %>
        <% else %>
          <%= link_to "Start Application", new_document_path, class: "btn btn-lg btn-primary" %>
        <% end %>  
    </div>
  </div>

  <div class="col-md-12 text-center back-buttons">
    <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-lg btn-default" %> 
    <%= link_to 'Back', users_path, class: "btn btn-lg btn-default" %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Vectron X-17 Wrist Computer</h1>
  </div>
</div>

<div class="row well well-lg">
  <div class="col-md-6">
    <h2>The Latest in Wearable Technology</h2>
    <p class="lead">Access all your files and communication apps
  		from a touchscreen with holo-projector.</p>
    <%= link_to "Register Now", new_user_path, class: "btn btn-lg btn-primary"  %>
  </div>
  <div class="col-md-6 hidden-sm hidden-xs">
    <%= image_tag("wrist_computer.jpg", class: "img-responsive") %>
  </div>
</div>

<div class="row text-center">
  <div class="col-md-4 col-sm-4 col-sm-offset-0 col-xs-10 col-xs-offset-1">
    <i class="glyphicon glyphicon-briefcase"></i>
    <h3>Book Today!</h3>
    <p>Even if you're traveling tomorrow, 
    	you can book right now and </p>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-6">
  	<i class="glyphicon glyphicon-random"></i>
  	<h3>Go Anywhere</h3>
  	<p>If you need to get to Starfleet today</p>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-6">
  	<i class="glyphicon glyphicon-send"></i>
  	<h3>RocketCar</h3>
  	<p>For cheapest fares, catch the</p>
  </div>
</div>